title: Nathan Wells
tagline: "Stats and Stocks"
theme: "09"
reverse: False
description: >I am a statistician and i like to trade stocks.

url: "http://ngwells.github.io/"
author:
  name: "Nathan Wells"
  github: "ngwells"


sidebar:
  - {item: Research, href: '/research', icon: 'cogs'}
  - {item: Publications, href: '/publications', icon: 'pencil-square'}
  - {item: Projects, href: '/projects', icon: 'puzzle-piece'}
  - {item: Software, href: '/software', icon: 'code'}
  - {item: Blog, href: '/blog', icon: 'archive'}


